# Nombre de la aplicacion
spring.application.name=scheduler

# Configuracion de Conexion a PostgreSQL
# (jdbc:postgresql://HOST:PUERTO/NOMBRE_BD)
spring.datasource.url=jdbc:postgresql://localhost:5432/citas_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA / Hibernate
# update: crea o actualiza automaticamente las tablas de la BD basandose en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formato_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

